<%@ Page Title="Inventory App" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Default.aspx.cs" Inherits="InventoryApp._Default" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">

    <div class="jumbotron">
        <div class="row">

            <div class="col-md-6 alert-info">
                <a><strong id="tgtWhatIsThis" class="alert-info"> What is this?</strong></a> 
                <div id="divWhatIsThis" class="alert-info" style="display:none">           
                This inventory control web app is a simple web form with a master page. Imagine working in a warehouse where shipments come in and out all day.  When shipments come in, you have to update what came in and how much, and from time to time will have to add new items you haven't received before. When shipments go out, you'll have to indicate how much has went out.  This app allows negative numbers to reflect when orders come in that exceed on-hand amounts. That is, a negative number indicates a backorder situation. 
                </div>
            </div>

            <div class="col-md-6 alert-info">
                <a><strong id="tgtUnderTheHood" class="alert-info"> What's going on under the hood?</strong></a>
                <div id ="divUnderTheHood" class="alert-info" style="display:none">
                <ul><li>The app has been made mobile responsive using bootstrap and its client side functionality is powered by jQuery.</li>
                    <li>The server side code is a mix of C# and ADO.net.</li>
                    <li>It uses a FileUpload control to allow user uploads of small JPEGs after a few rounds of validation occurs (controlling for file type, size, etc.)</li>
                    <li>It uses ADO.net commands to communicate to a MS SQL server. Each command incorporates SQL injection defense strategies.</li>
                <li>The inventory view itself is created dynamically using a datagrid control with its default formatting and columns ripped out to offer a more visually pleasing experience. </li>
                </ul></div>
            </div>
        </div>

        <h1>Inventory Management</h1>
        
        <asp:Label ID="lblStatusMessage"  runat="server" ForeColor="red"></asp:Label>
        
        <div class="row">

            <div class="col-md-6">
                <h2>Exisiting Inventory </h2>
                <asp:GridView ID="GridView1" runat="server" AutoGenerateDeleteButton="True" AutoGenerateColumns="False" DataKeyNames="PartID" DataSourceID="SqlDataSource1" BorderStyle="None" ShowHeader="False" GridLines="None">
                    <Columns>
                        <asp:TemplateField>
                            <ItemTemplate>
                                <table class="table table-hover" style="border: 1px solid grey; margin: 20px; padding: 5px; background-color: white">
                                    <tr>
                                        <td style="width: 175px;">
                                            <asp:Image ID="imgSpace" ImageUrl='<%# Eval("ImagePath")%>' Width="150px" runat="server" /><br />
                                        </td>

                                        <td style="width: 200px">
                                            <table>
                                                <tr>
                                                    <td>
                                                        <b>Part Name:</b>
                                                    </td>
                                                    <td>
                                                        <asp:Label ID="lblPartName" runat="server" Text='<%#Eval("PartName") %>'></asp:Label>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <b>Quantity in Stock:</b>
                                                    </td>
                                                    <td>
                                                        <asp:Label ID="lblQuantityInStock" runat="server" Text='<%#Eval("QuantityInStock") %>'></asp:Label>
                                                    </td>

                                                </tr>
                                            </table>
                                        </td>
                                    </tr>

                                </table>
                            </ItemTemplate>


                        </asp:TemplateField>
                    </Columns>
                    <HeaderStyle BorderStyle="None" />
                </asp:GridView>

                <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:dbInventoryAppConnectionString %>" DeleteCommand="DELETE FROM [tblInventory] WHERE [PartID] = @PartID" InsertCommand="INSERT INTO [tblInventory] ([PartName], [QuantityInStock], [ImagePath]) VALUES (@PartName, @QuantityInStock, @ImagePath)" SelectCommand="SELECT * FROM [tblInventory]" UpdateCommand="UPDATE [tblInventory] SET [PartName] = @PartName, [QuantityInStock] = @QuantityInStock, [ImagePath] = @ImagePath WHERE [PartID] = @PartID">
                    <DeleteParameters>
                        <asp:Parameter Name="PartID" Type="Int32" />
                    </DeleteParameters>
                    <InsertParameters>
                        <asp:Parameter Name="PartName" Type="String" />
                        <asp:Parameter Name="QuantityInStock" Type="Int32" />
                        <asp:Parameter Name="ImagePath" Type="String" />
                    </InsertParameters>
                    <UpdateParameters>
                        <asp:Parameter Name="PartName" Type="String" />
                        <asp:Parameter Name="QuantityInStock" Type="Int32" />
                        <asp:Parameter Name="ImagePath" Type="String" />
                        <asp:Parameter Name="PartID" Type="Int32" />
                    </UpdateParameters>
                </asp:SqlDataSource>

            </div>

            <div class="col-md-6">
                <div id="AddInventory">
                    <h3>Add Inventory</h3>
                    <asp:Label ID="Label1" runat="server" Text="Select Part"></asp:Label>
                    <br />

                    <!-- I have to use a class here, not an ID, and make sure it is unique throughout the page, because jQuery has problems getting ID of a server side control from an external javascript file. This solution works, but may present performance problems in larger apps. I will revisit this later. -->
                    <asp:DropDownList class="dropdownPartName" ID="DropdownAddPartName" AppendDataBoundItems="true" runat="server" DataSourceID="SqlDataSource1" DataTextField="PartName" DataValueField="PartName">
                        <asp:ListItem Selected="True" Value="-1">Please select</asp:ListItem>
                        <asp:ListItem>Other</asp:ListItem>
                    </asp:DropDownList><br />
                    <asp:Label ID="Label2" runat="server" Text="Quantity"></asp:Label><br />
                    <asp:TextBox ID="txtboxQuantity" TextMode="Number" MaxLength="4" runat="server" Width="75px"></asp:TextBox><br />
                    <div id="addNewPartDiv" style="display:none; ">
                        <asp:Label ID="Label5" runat="server" Text="New Part Name:"></asp:Label><br />
                        <asp:TextBox ID="txtboxNewPartName" runat="server" MaxLength="20"></asp:TextBox><br />
                        <asp:FileUpload ID="FileUpload1" runat="server" ToolTip="150px by 150px work best. Please keep the image to under 10kb." ValidateRequestMode="Enabled" />
                    </div>

                    <asp:Button ID="btnAdd" CssClass="btn btn-primary" runat="server" Text="Add" OnClick="btnAdd_Click" />



                    <a id="lnkRemoveInventory">Looking to Withdraw from Inventory? </a>
                    <br />
                    <br />

                </div>
                <div id="RemoveInventory"  style="display:none; border: 5px solid grey; padding: 5px; border-radius: 20px; margin: 25px">
                    <h3>Withdraw Parts</h3>
                    <asp:Label ID="Label3" runat="server" Text="Part Name"></asp:Label><asp:DropDownList ID="dropdownPartNameInInventory" runat="server" DataSourceID="SqlDataSource1" DataTextField="PartName" DataValueField="PartName">
                        <asp:ListItem Selected="True" Value="-1">Please Select</asp:ListItem>
                    </asp:DropDownList>
                    <asp:SqlDataSource ID="SqlDataSource2" runat="server"></asp:SqlDataSource>
                    <br />
                    <asp:Label ID="Label4" runat="server" Text="Quantity Withdrawn"></asp:Label><asp:TextBox ID="txtboxWithdraw" Width="75px" TextMode="Number" runat="server"></asp:TextBox><br />
                    <asp:Button ID="btnWithdraw" CssClass="btn btn-primary" runat="server" Text="Withdraw Parts" OnClick="btnWithdraw_Click" /><br />
                    <br />
                    <a id="lnkAddInventory">Looking to Add Inventory? </a>
                    <br />

                </div>
            </div>
        </div>
        </div>
  
    <script src="Scripts/jquery-3.1.1.min.js"></script>
    <script src="Scripts/btnManager.js"></script>

</asp:Content>
